"""driver_pole_directions_scenario_axis_poles

Revision ID: 411a237e3663
Revises: a6ec0e7b9e46
Create Date: 2026-04-14 14:54:43.709302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '411a237e3663'
down_revision: Union[str, None] = 'a6ec0e7b9e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
