"""directional_trend_driver_scenario_poles

Revision ID: a6ec0e7b9e46
Revises: 0006
Create Date: 2026-04-14 14:54:38.195433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a6ec0e7b9e46'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.add_column('drivers', sa.Column('pole_high_direction', sa.Text(), nullable=True))
    op.add_column('drivers', sa.Column('pole_low_direction', sa.Text(), nullable=True))
    op.drop_index('ix_drivers_theme_id', table_name='drivers')
    op.drop_index('ix_raw_documents_content_hash', table_name='raw_documents')
    op.drop_index('ix_scenario_axes_theme_id', table_name='scenario_axes')
    op.drop_index('ix_scenario_drafts_theme_id', table_name='scenario_drafts')
    op.drop_index('ix_scenario_indicators_scenario_id', table_name='scenario_indicators')
    op.drop_index('ix_scenario_indicators_theme_id', table_name='scenario_indicators')
    op.add_column('scenarios', sa.Column('axis1_pole', sa.String(length=10), nullable=True))
    op.add_column('scenarios', sa.Column('axis2_pole', sa.String(length=10), nullable=True))
    op.drop_index('ix_signals_theme_id', table_name='signals')
    op.drop_index('ix_sources_theme_id', table_name='sources')
    op.add_column('trends', sa.Column('direction', sa.Text(), nullable=True))
    op.add_column('trends', sa.Column('counterpole', sa.Text(), nullable=True))
    op.drop_index('ix_trends_cluster_id', table_name='trends')
    op.drop_index('ix_trends_theme_id', table_name='trends')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_trends_theme_id', 'trends', ['theme_id'], unique=False)
    op.create_index('ix_trends_cluster_id', 'trends', ['cluster_id'], unique=False)
    op.drop_column('trends', 'counterpole')
    op.drop_column('trends', 'direction')
    op.create_index('ix_sources_theme_id', 'sources', ['theme_id'], unique=False)
    op.create_index('ix_signals_theme_id', 'signals', ['theme_id'], unique=False)
    op.drop_column('scenarios', 'axis2_pole')
    op.drop_column('scenarios', 'axis1_pole')
    op.create_index('ix_scenario_indicators_theme_id', 'scenario_indicators', ['theme_id'], unique=False)
    op.create_index('ix_scenario_indicators_scenario_id', 'scenario_indicators', ['scenario_id'], unique=False)
    op.create_index('ix_scenario_drafts_theme_id', 'scenario_drafts', ['theme_id'], unique=False)
    op.create_index('ix_scenario_axes_theme_id', 'scenario_axes', ['theme_id'], unique=False)
    op.create_index('ix_raw_documents_content_hash', 'raw_documents', ['content_hash'], unique=False)
    op.create_index('ix_drivers_theme_id', 'drivers', ['theme_id'], unique=False)
    op.drop_column('drivers', 'pole_low_direction')
    op.drop_column('drivers', 'pole_high_direction')
    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='system_settings_pkey')
    )
    # ### end Alembic commands ###
